packages:
  - "bundlers/*"
  - "blockexplorer"
  - "cli"
  - "config"
  - "core"
  - "blockexplorer"
  - "docs"
  - "e2e"
  - "ethers"
  - "examples/*"
  - "experimental/*"
  - "schemas"
  - "requests"
  - "revm"
  - "schemas"
  - "ts-plugin"
  - "tsconfig"
  - "viem"

