on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  merge_group:

name: E2E

jobs:
  e2e:
    name: Playwright E2E
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: "Setup"
        uses: ./.github/actions/setup

      - name: Run Playwright
        run: pnpm i && npx playwright install && pnpm nx affected --target=e2e:ci
        env:
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
          VITE_RPC_URL_1: ${{ secrets.RPC_URL_MAINNET }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
